let n1=parseFloat(prompt("ingrese la nota 1 valor 20%"))
let n2=parseFloat(prompt("ingrese la nota 2 valor 20%"))
let n3=parseFloat(prompt("ingrese la nota 3 valor 30%"))
let n4=parseFloat(prompt("ingrese la nota 4 valor 30%"))
alert("el promedio es: " +  ((n1*0.2)+(n2*0.2)+(n3*0.3)+(n4*0.3)))