let exmat = parseFloat(prompt('ingrese cuanto sacó en el exámen de matemáticas: '))
let tarea1mat = parseFloat(prompt('ingrese la nota de la primera tarea de matemáticas: '))
let tarea2mat = parseFloat(prompt('ingrese la nota de la segunda tarea de matemáticas: '))
let tarea3mat = parseFloat(prompt('ingrese la nota de la tercera tarea de matemáticas: '))
let exfis = parseFloat(prompt('ingrese cuanto sacó en el exámen de física: '))
let tarea1fis = parseFloat(prompt('ingrese la nota de la primera tarea de física: '))
let tarea2fis = parseFloat(prompt('ingrese la nota de la segunda tarea de física: '))
let examqui = parseFloat(prompt('ingrese cuanto sacó en el exámen de química: '))
let tarea1qui = parseFloat(prompt('ingrese la nota de la primera tarea de química: '))
let tarea2qui = parseFloat(prompt('ingrese la nota de la segunda tarea de química: '))
let tarea3qui = parseFloat(prompt('ingrese la nota de la tercera tarea de química: '))
let notamat = (exmat*0.9 + (((tarea1mat + tarea2mat + tarea3mat)/3)*0.1))
let notfis = (exfis*0.8 + ((tarea1fis + tarea2fis)/2)*0.2)
let notqui = (examqui*0.85 + ((tarea1qui + tarea2qui + tarea3qui)/3)*0.15)
alert('la nota total de matemáticas es: ' + notamat+" la nota de física es: " + notfis+" la nota de química es: " + notqui)
alert("el promedio es: " + (notamat+notfis+notqui)/3)
